config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :polls do
    resources :questions
    resources :replies, only: [ :new, :create ]
  end

  root 'polls#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :reply
  belongs_to :question
  belongs_to :possible_answer
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  # Relationships
  has_many :questions
  has_many :replies

  # Validations
  validates_presence_of :title

  def serialize_for_graph
    PollSerializer.count_per_month(self).to_json
  end
end

app/models/possible_answer.rb
class PossibleAnswer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :poll
  has_many :possible_answers
  has_many :answers

  validates_presence_of :title, :kind

  accepts_nested_attributes_for :possible_answers, reject_if: proc { |attributes| attributes['title'].blank? }

  def serialize_for_graph
    PollSerializer.answers_per_question(self).to_json
  end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :poll
  has_many :answers

  accepts_nested_attributes_for :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [ :index ]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title)
    end

    def authenticate!
      authenticate_user!

      unless current_user.admin?
        redirect_to root_path, alert: "You don't have enough privileges to run that operation."
      end
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_poll
  before_action :set_kind_options, only: [ :new, :create, :edit, :update ]

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = @poll.questions.build
    7.times { @question.possible_answers.build }
  end

  def edit
  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @poll, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to @poll, notice: 'Question dropped.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:poll_id, :title, :kind, { possible_answers_attributes: [ :question_id, :title ] } )
    end

    def set_kind_options
      @kind_options = [ [ "Open answer", "open" ], [ "Choice", "choice"] ]
    end

    def set_poll
      @poll = Poll.find params[:poll_id]
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_poll

  def new
    @reply = @poll.replies.build
    @poll.questions.each do |question|
      @reply.answers.build question: question
    end
  end

  def create
    @reply = @poll.replies.build reply_params

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @poll, notice: "Thank you for taking the poll." }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_poll
    @poll = Poll.find params[:poll_id]
  end

  def reply_params
    params.require(:reply).permit({ answers_attributes: [ :value, :question_id, :possible_answer_id ] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/application/_nav.html.haml
%nav.navbar.navbar-default.navbar-static-top{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#nav", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Tutspolls", root_path, class: "navbar-brand"

    #nav.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          =link_to polls_path do
            %span.glyphicon.glyphicon-flag
            Polls

      %ul.nav.navbar-nav.navbar-right
        -if current_user
          %li
            %span.navbar-text Signed in as #{current_user.email}
          %li
            =link_to destroy_session_path('user'), method: :delete do
              %span.glyphicon.glyphicon-log-out
              Sign out
        -else
          %li
            =link_to new_session_path('user') do
              %span.glyphicon.glyphicon-log-in
              Sign in

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tutspolls
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'http://google.com/jsapi'
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =javascript_include_tag '//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js'
    =csrf_meta_tags
  %body
    =render 'nav'
    .container
      =content_tag :div, flash[:notice], class: "flash bg-success" if flash[:notice]
      =content_tag :div, flash[:alert], class: "flash bg-danger" if flash[:alert]

      =yield

    =yield :footer

app/views/polls/_form.html.haml
= form_for @poll do |f|
  - if @poll.errors.any?
    #error_explanation
      %h3.text-danger= "#{pluralize(@poll.errors.count, "error")} prohibited this poll from being saved:"
      %ul
        - @poll.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :title
    = f.text_field :title, class: "form-control input-lg"
  %p

    = f.submit 'Save', class: "btn btn-primary"

app/views/polls/_questions.html.haml
-if @poll.questions.any?
  %ul
    -@poll.questions.each do |question|
      %li
        =question.title
        =link_to "Drop question", poll_question_path(@poll, question), method: :delete
        %ul
          -question.possible_answers.each do |possible_answer|
            %li=possible_answer.title

-else
  %p.bg-info.flash No questions.

%p.btn-group
  =link_to 'Add question', new_poll_question_path(@poll), class: "btn btn-default"
  =link_to 'Edit', edit_poll_path(@poll), class: "btn btn-default"
  =link_to 'Answer', new_poll_reply_path(@poll), class: "btn btn-default"

app/views/polls/_replies.html.haml
-@poll.replies.each do |reply|
  .col-md-6
    .panel.panel-default
      .panel-heading.text-right
        =time_ago_in_words reply.created_at
      .panel-body
        %dl
          -reply.answers.each do |answer|
            %dt=answer.question.title
            %dd
              =answer.value.present? ? answer.value : answer.possible_answer.title

app/views/polls/_stats.html.haml
#polls_per_month
  :javascript
    (function($) {
      $(function() {
        var selector = "#polls_per_month";
        var data = #{@poll.serialize_for_graph};

        Graph.column(selector,data);
      });
    })(jQuery);

#answers_per_question
  -@poll.questions.each do |question|
    -if question.kind == "choice"
      .answer-per-question{id: "answers-per-question-#{question.id}"}
        :javascript
          (function($) {
            $(function() {
              var selector = "#answers-per-question-#{question.id}";
              var data = #{question.serialize_for_graph};

              Graph.pie(selector,data);
            });
          })(jQuery);

-content_for :footer do
  :javascript
    google.setOnLoadCallback(function() {
      Graph.instances.forEach(function(instance) {
        instance.render();
      });
    });

app/views/polls/edit.html.haml
%h1 Editing poll

= render 'form'

= link_to 'Show', @poll
\|
= link_to 'Back', polls_path

app/views/polls/index.html.haml
%h1 All polls

- unless @polls.any?
  %p.bg-info.flash No polls.

%ul.clearfix.polls
  - @polls.each do |poll|
    %li.col-md-6.polls-poll
      .polls-poll-detail
        %h2
          =link_to poll.title, new_poll_reply_path(poll)
          =link_to "Manage", poll, class: "label label-default" if current_user && current_user.admin?

  -if current_user && current_user.admin?
    %li.col-md-6.polls-poll
      .polls-poll-detail
        %h2
          = link_to '+', new_poll_path

app/views/polls/new.html.haml
%h1 New poll

= render 'form'

= link_to 'Back', polls_path

app/views/polls/show.html.haml
%h1=@poll.title

%ul.nav.nav-tabs
  %li.active
    =link_to "#tab-questions", data: { toggle: "tab" } do
      %span.glyphicon.glyphicon-th-list
      Questions
  %li
    =link_to "#tab-replies", data: { toggle: "tab" } do
      %span.glyphicon.glyphicon-list-alt
      Replies

  %li
    =link_to "#tab-stats", data: { toggle: "tab" } do
      %span.glyphicon.glyphicon-stats
      Stats

.tab-content
  #tab-questions.tab-pane.active
    =render "questions"

  #tab-replies.tab-pane
    =render "replies"

  #tab-stats.tab-pane
    =render "stats"

app/views/questions/_form.html.haml
= form_for [@poll, @question] do |f|
  - if @question.errors.any?
    #error_explanation
      %h3.text-danger= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  %p
    =f.label :title
    =f.text_field :title, class: "form-control input-lg"

  %p
    %label What kind of question?
  .radio
    -@kind_options.each do |option|
      %label
        =f.radio_button :kind, option[1]
        =option[0]

  %p
    %label Specify some choices:

  =f.fields_for :possible_answers do |c|
    %p
      =c.text_field :title, placeholder: "Type your choice", class: "form-control"

  %p
    =f.hidden_field :poll_id
    =f.submit 'Save', class: "btn btn-primary"

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %tr
    %th Poll
    %th Title
    %th Type
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= question.poll
      %td= question.title
      %td= question.type
      %td= link_to 'Show', question
      %td= link_to 'Edit', edit_question_path(question)
      %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1
  Add new question to
  =link_to @poll.title, @poll

= render 'form'

%p= link_to 'Back', @poll

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Poll:
  = @question.poll
%p
  %b Title:
  = @question.title
%p
  %b Type:
  = @question.type

= link_to 'Edit', edit_poll_question_path(@poll, @question)
\|
= link_to 'Back', @poll

app/views/replies/_choice.html.haml
%label=c.object.question.title
.radio
  -c.object.question.possible_answers.each do |possible_answer|
    %p
      %label
        =possible_answer.title
        =c.radio_button :possible_answer_id, possible_answer.id
        =c.hidden_field :question_id

app/views/replies/_open.html.haml
%p
  =c.label :value, c.object.question.title
  =c.text_field :value, class: "form-control"
  =c.hidden_field :question_id

app/views/replies/create.html.haml
%h1 Replies#create
%p Find me in app/views/replies/create.html.haml

app/views/replies/new.html.haml
%h1=@poll.title

=form_for [ @poll, @reply ] do |f|
  =f.fields_for :answers do |c|
    =render c.object.question.kind, c: c

  =f.submit "Finish poll", class: "btn btn-primary"